apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: hellogopher # use the hellogopher namespace
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate  
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          #Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: hellogopher #we added namespace for hellogopher
spec:
  ports:
  - port: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configs
  namespace: hellogopher
data:
  DATABASE_USERNAME: root
  DATABASE_NAME: test

---

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: hellogopher
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=



