apiVersion: apps/v1  #Which version of the Kubernetes API you're using to create this object
kind: Deployment #what kind of object you want to create [deployment, sevices ]
metadata: # Data that helps to uniquely identify the object
  name: hellogopher
spec: # what state you desire for the object
  selector: # 
    matchLabels: #matchLabels is a map of {key, value} pairs
      app: hellogopher
  replicas: 1 #tells the deplyment to run 1 pod
  template: #when creating new pods, this template will be used
    metadata:
      labels: #labels used when searching / managing deployments
        app: hellogopher
    spec:
      containers:
      - name: hellogopher # Name of the Container
        image: santosh/hellogopher:5.0 # Important, to not use latest tag as it will try DOckerhub then
        imagePullPolicy: IfNotPresent # Will only pull from DockerHub if not present already in Local docker
        envFrom:
        - configMapRef:
            name: database-configs # just specify your configmap name
        env:
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef: # This is used to fetch value from secret, should be base64 encoded
              name: database-secrets # Name of our secrets object
              key: DATABASE_PASSWORD # The secret key to fetch value from
        resources: # Here we start the Resource section 
          requests: # Requests are the minimum available resources a Node needs to be accepted as a valid node
            memory: "1Mi"
            cpu: "50m"
          limits: # Limits is the maximum amount of resource the pods are allowed to use
            memory: "10Mi"
            cpu: "100m" # 0.1 Is not allowed, instead we use 100m which is the same
      
        ports: # Ports to Expose
        - containerPort: 8080  
        readinessProbe:
          initialDelaySeconds: 5 #Time before starting to proble sttus
          timeoutSeconds: 1 #Time to wait before timeout
          #HTTP proble
          httpGet:
            path: / # the path we use to proble
            port: 8080 
        livenessProbe:
          initialDelaySeconds: 5 # Time before starting a Proble status
          timeoutSeconds: 1 #TIme to wait before timeout
          failureThreshold: 3 # How many times it can fail before restarting
          # HTTP proble
          httpGet:  
            path: / #the path we use to probe
            port: 8080

